# .bashrc - Custom bash configuration
# Generated by arch-setup script

export HISTCONTROL=ignoredups
export HISTSIZE=1000
export HISTFILESIZE=2000

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'

# Colors
export CLICOLOR=1
export LS_COLORS='di=34:ln=31:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=41;30:sg=46;30:tw=42;30:ow=43;30'

# Custom prompt
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
